---
- hosts: loadbalancers
  become: yes
  tasks:
  - name: Install NGINX
    apt:
      name: nginx
      update_cache: yes

  - name: Push NGINX Load Balancer config
    copy:
      src: files/loadbalancerConfig
      dest: /etc/nginx/sites-available/default
      mode: 644
      owner: root
      group: root
    notify:
    - restart nginx

  handlers:
  - name: restart nginx
    service:
      name: nginx
      state: restarted

