---
- hosts: nodejs
  become: yes
  vars:
    NODEJS_VERSION: "10"
    USER_AND_GROUP_NAME: "ldap_api"
  tasks:
  - name: Install the gpg key for nodejs
    apt_key:
      url: "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"
      state: present

  - name: Add the `NodeJS` repos
    apt_repository:
      repo: "deb https://deb.nodesource.com/node_{{ NODEJS_VERSION }}.x {{ ansible_distribution_release }} main"
      state: present
      update_cache: yes

  - name: Install `NodeJS`
    apt:
      name: nodejs
      update_cache: yes
      state: latest

  - name: Install `make`
    apt:
      name: make
      update_cache: yes
      state: latest

  - name: Create group `{{ USER_AND_GROUP_NAME }}`
    group:
      name: "{{ USER_AND_GROUP_NAME }}"

  - name: Create user `{{ USER_AND_GROUP_NAME }}` and add to the group `{{ USER_AND_GROUP_NAME }}`
    user:
      name: "{{ USER_AND_GROUP_NAME }}"
      group: "{{ USER_AND_GROUP_NAME }}"
      system: yes

  - name: Create directory `/var/www/{{ USER_AND_GROUP_NAME }}`
    file:
      path: "/var/www/{{ USER_AND_GROUP_NAME }}"
      state: directory

  - name: Set permissions on `/var/www/{{ USER_AND_GROUP_NAME }}`
    file:
      path: "/var/www/{{ USER_AND_GROUP_NAME }}"
      owner: "{{ USER_AND_GROUP_NAME }}"
      group: "{{ USER_AND_GROUP_NAME }}"

  - name: Add `ldap_api.service` config
    copy:
      src: files/ldap_api.service
      dest: /etc/systemd/system/

  - name: Enable `ldap_api.service`
    systemd:
      name: ldap_api.service
      enabled: true